// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9r-VTy0k164UdGvljAnbjQpc-fc1UuDM',
    appId: '1:1069792230547:web:cb01d0659b1fa53b8ce166',
    messagingSenderId: '1069792230547',
    projectId: 'adinda-marketplace',
    authDomain: 'adinda-marketplace.firebaseapp.com',
    storageBucket: 'adinda-marketplace.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0hPCeN7pnJwgw_lIFSmEyySh07FLUqns',
    appId: '1:1069792230547:android:908db576d742fb558ce166',
    messagingSenderId: '1069792230547',
    projectId: 'adinda-marketplace',
    storageBucket: 'adinda-marketplace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBenC47qK6abaEoshXuLFGTc9LLgubBt2o',
    appId: '1:1069792230547:ios:68e15cb10089aa698ce166',
    messagingSenderId: '1069792230547',
    projectId: 'adinda-marketplace',
    storageBucket: 'adinda-marketplace.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBenC47qK6abaEoshXuLFGTc9LLgubBt2o',
    appId: '1:1069792230547:ios:68e15cb10089aa698ce166',
    messagingSenderId: '1069792230547',
    projectId: 'adinda-marketplace',
    storageBucket: 'adinda-marketplace.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9r-VTy0k164UdGvljAnbjQpc-fc1UuDM',
    appId: '1:1069792230547:web:0691cd36f85d760c8ce166',
    messagingSenderId: '1069792230547',
    projectId: 'adinda-marketplace',
    authDomain: 'adinda-marketplace.firebaseapp.com',
    storageBucket: 'adinda-marketplace.firebasestorage.app',
  );

}